update

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -24,4 +24,21 @@ jobs:
       - name: Restart Application
         run: |
           ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} \
-          "cd /root/10MS_Booking-management && sudo git pull && sudo pm2 reload all"
+          "cd /root/10MS_Booking-management && sudo git pull \
+            
+            echo '🔹 Installing Node.js (if missing)...'
+            if ! command -v node >/dev/null 2>&1; then
+              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
+              apt-get install -y nodejs
+            fi
+
+            echo '🔹 Installing PM2 (if missing)...'
+            if ! command -v pm2 >/dev/null 2>&1; then
+              npm install -g pm2
+            fi
+
+            echo '🔹 Starting or reloading app...'
+            if pm2 list'; then
+              pm2 reload all
+
+          "
